# Generated by Django 2.2.7 on 2021-03-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_collection_noteconnectionsender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripeSubscriptionID',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
