# Generated by Django 2.2.7 on 2021-03-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210301_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='stripeSubscriptionID',
            field=models.TextField(null=True),
        ),
    ]
