# Generated by Django 2.2.7 on 2021-03-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_profile_stripesubscriptionid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='payment_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
