# Generated by Django 2.2.7 on 2021-03-29 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_profile_free_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='free_account',
            new_name='has_free_account',
        ),
    ]
