# Generated by Django 2.2.7 on 2021-03-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210329_1505'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easiness', models.FloatField(null=True)),
                ('interval', models.IntegerField(null=True)),
                ('repetitions', models.IntegerField(null=True)),
                ('review_date', models.DateTimeField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='learning_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.LearningData'),
        ),
    ]
