# Generated by Django 2.2.7 on 2021-03-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210329_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='learning_objects',
            field=models.ManyToManyField(blank=True, to='main.LearningData'),
        ),
    ]
