# Generated by Django 2.2.7 on 2021-03-29 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_collection_learning_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='learning_data',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.LearningData'),
        ),
    ]
