# Generated by Django 2.2.7 on 2021-03-29 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210329_1820'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningdata',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Profile'),
            preserve_default=False,
        ),
    ]
