# Generated by Django 2.2.7 on 2021-03-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningdata',
            name='review_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
