# Generated by Django 2.2.7 on 2021-03-30 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210330_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='open_learning_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.LearningData'),
        ),
    ]
