# Generated by Django 2.2.7 on 2021-04-04 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_collection_current_learning_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='current_learning_objects',
            field=models.ManyToManyField(related_name='learning_queue', to='main.LearningData'),
        ),
    ]
