# Generated by Django 2.2.7 on 2021-07-17 17:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_collection_learning_block_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='learning_block_created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 17, 17, 8, 53, 421445, tzinfo=utc)),
        ),
    ]
