# Generated by Django 2.2.7 on 2021-07-18 07:28

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20210717_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='learning_block_created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 18, 7, 28, 17, 767872, tzinfo=utc)),
        ),
    ]
