# Generated by Django 2.2.7 on 2021-07-18 07:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210718_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='learning_block_created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
