# Generated by Django 2.2.7 on 2021-07-18 07:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20210718_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='learning_block_created_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 7, 18, 7, 35, 18, 827114, tzinfo=utc)),
        ),
    ]
