# Generated by Django 2.2.7 on 2021-07-18 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_auto_20210718_0736'),
        ('main', '0027_auto_20210718_0735'),
    ]

    operations = [
    ]
